// src/UI/Web/Angular/src/app/features/reviews/pages/reviews.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { CustomerReviewService } from '../../../core/services/data-services';
import { CustomerReviewResponse } from '../../../shared/models/models';

@Component({
  selector: 'app-reviews',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './reviews.component.html'
})
export class ReviewsComponent implements OnInit {
  private reviewService = inject(CustomerReviewService);

  reviews = signal<CustomerReviewResponse[]>([]);
  loading = signal(false);
  totalCount = signal(0);
  page = signal(1);
  pageSize = signal(8);

  // Filters
  productName = signal('');
  minRating = signal<number | undefined>(undefined);
  isApproved = signal<boolean | undefined>(undefined);

  ngOnInit() {
    this.loadReviews();
  }

  loadReviews() {
    this.loading.set(true);
    this.reviewService.getReviews(
      this.page(), 
      this.pageSize(), 
      this.productName(), 
      this.minRating(), 
      this.isApproved()
    ).subscribe({
      next: (res) => {
        this.reviews.set(res.items);
        this.totalCount.set(res.totalCount);
        this.loading.set(false);
      },
      error: () => this.loading.set(false)
    });
  }

  handleApprove(id: string, approve: boolean) {
    this.reviewService.approve(id, approve).subscribe(() => {
      this.loadReviews();
    });
  }

  handleDelete(id: string) {
    if (confirm('Tem certeza que deseja excluir esta avaliação?')) {
      this.reviewService.delete(id).subscribe(() => {
        this.loadReviews();
      });
    }
  }

  getStars(rating: number): number[] {
    return Array(rating).fill(0);
  }

  getEmptyStars(rating: number): number[] {
    return Array(5 - rating).fill(0);
  }
}

<div class="p-10 max-w-7xl mx-auto space-y-10 animate-in fade-in duration-700">
  <!-- Header -->
  <header class="flex justify-between items-end">
    <div>
      <h1 class="text-6xl font-black text-gray-900 tracking-tighter">Customer Reviews</h1>
      <p class="text-gray-500 mt-4 font-medium text-xl">Gerenciamento e moderação de avaliações (MongoDB).</p>
    </div>
    <div class="flex gap-4">
      <div class="bg-white p-2 rounded-2xl shadow-sm border border-gray-100 flex gap-2">
        <button (click)="isApproved.set(undefined); loadReviews()" 
                [class]="!isApproved() ? 'bg-gray-900 text-white' : 'text-gray-500 hover:bg-gray-50'"
                class="px-6 py-2 rounded-xl font-bold transition-all">Todos</button>
        <button (click)="isApproved.set(true); loadReviews()" 
                [class]="isApproved() === true ? 'bg-green-600 text-white' : 'text-gray-500 hover:bg-gray-50'"
                class="px-6 py-2 rounded-xl font-bold transition-all">Aprovados</button>
        <button (click)="isApproved.set(false); loadReviews()" 
                [class]="isApproved() === false ? 'bg-amber-500 text-white' : 'text-gray-500 hover:bg-gray-50'"
                class="px-6 py-2 rounded-xl font-bold transition-all">Pendentes</button>
      </div>
    </div>
  </header>

  <!-- Filters -->
  <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
    <div class="relative group">
      <input type="text" [(ngModel)]="productName" (keyup.enter)="loadReviews()"
             placeholder="Buscar por produto..."
             class="w-full pl-14 pr-6 py-5 bg-white border-none rounded-3xl shadow-xl shadow-gray-200/50 font-bold text-gray-700 focus:ring-2 focus:ring-primary-500 transition-all outline-none">
      <span class="absolute left-6 top-1/2 -translate-y-1/2 text-gray-300 group-focus-within:text-primary-500 transition-colors">🔍</span>
    </div>

    <div class="relative group">
      <select [(ngModel)]="minRating" (change)="loadReviews()"
              class="w-full pl-14 pr-6 py-5 bg-white border-none rounded-3xl shadow-xl shadow-gray-200/50 font-bold text-gray-700 focus:ring-2 focus:ring-primary-500 transition-all outline-none appearance-none">
        <option [ngValue]="undefined">Mínimo de Estrelas</option>
        <option [ngValue]="1">⭐ 1+ Estrela</option>
        <option [ngValue]="2">⭐⭐ 2+ Estrelas</option>
        <option [ngValue]="3">⭐⭐⭐ 3+ Estrelas</option>
        <option [ngValue]="4">⭐⭐⭐⭐ 4+ Estrelas</option>
        <option [ngValue]="5">⭐⭐⭐⭐⭐ 5 Estrelas</option>
      </select>
      <span class="absolute left-6 top-1/2 -translate-y-1/2 text-gray-300 group-focus-within:text-primary-500 transition-colors">⭐</span>
    </div>
  </div>

  <!-- Loading State -->
  <div *ngIf="loading()" class="flex flex-col items-center justify-center py-32 space-y-6">
    <div class="w-16 h-16 border-4 border-primary-100 border-t-primary-600 rounded-full animate-spin"></div>
    <p class="text-gray-400 font-black animate-pulse">CARREGANDO AVALIAÇÕES...</p>
  </div>

  <!-- Empty State -->
  <div *ngIf="!loading() && reviews().length === 0" class="bg-white rounded-[3rem] p-32 text-center shadow-2xl shadow-gray-100 border border-gray-50">
    <div class="text-8xl mb-8">📭</div>
    <h3 class="text-3xl font-black text-gray-900">Nenhuma avaliação encontrada</h3>
    <p class="text-gray-400 mt-4 font-medium">Tente ajustar seus filtros para encontrar o que procura.</p>
  </div>

  <!-- Content Grid -->
  <div *ngIf="!loading() && reviews().length > 0" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
    <div *ngFor="let review of reviews()" 
         class="bg-white p-8 rounded-[2.5rem] shadow-xl hover:shadow-2xl transition-all border border-gray-50 flex flex-col justify-between group">
      
      <div>
        <div class="flex justify-between items-start mb-6">
          <div class="flex gap-0.5">
            <span *ngFor="let s of getStars(review.rating)" class="text-amber-400 text-lg">★</span>
            <span *ngFor="let s of getEmptyStars(review.rating)" class="text-gray-100 text-lg">★</span>
          </div>
          <span *ngIf="review.isVerifiedPurchase" 
                class="bg-green-50 text-green-600 text-[10px] font-black px-3 py-1 rounded-full uppercase tracking-widest">
            Verificado
          </span>
        </div>

        <h4 class="text-xl font-black text-gray-900 mb-2 leading-tight group-hover:text-primary-600 transition-colors">{{ review.title }}</h4>
        <p class="text-gray-500 text-sm font-medium line-clamp-3 mb-6">{{ review.comment }}</p>
      </div>

      <div class="space-y-6">
        <div class="flex items-center gap-4 py-4 border-t border-gray-50">
          <div class="w-10 h-10 bg-primary-50 rounded-xl flex items-center justify-center text-primary-600 font-black text-xs">
            {{ review.customerName[0].toUpperCase() }}
          </div>
          <div class="min-w-0">
            <p class="text-sm font-black text-gray-900 truncate">{{ review.customerName }}</p>
            <p class="text-[10px] text-gray-400 font-bold uppercase truncate">{{ review.productName }}</p>
          </div>
        </div>

        <div class="flex gap-3">
          <button *ngIf="!review.isApproved" (click)="handleApprove(review.id, true)"
                  class="flex-1 py-3 bg-green-50 text-green-600 rounded-xl font-black text-[10px] uppercase tracking-widest hover:bg-green-600 hover:text-white transition-all shadow-sm">
            Aprovar
          </button>
          <button *ngIf="review.isApproved" (click)="handleApprove(review.id, false)"
                  class="flex-1 py-3 bg-amber-50 text-amber-600 rounded-xl font-black text-[10px] uppercase tracking-widest hover:bg-amber-500 hover:text-white transition-all shadow-sm">
            Rejeitar
          </button>
          <button (click)="handleDelete(review.id)"
                  class="p-3 bg-rose-50 text-rose-600 rounded-xl font-black hover:bg-rose-600 hover:text-white transition-all shadow-sm">
            🗑️
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- Pagination -->
  <footer *ngIf="!loading() && totalCount() > pageSize()" class="flex justify-center pt-10">
    <div class="bg-white p-2 rounded-2xl shadow-xl border border-gray-50 flex gap-2">
      <button [disabled]="page() === 1" (click)="page.set(page() - 1); loadReviews()"
              class="px-6 py-3 rounded-xl font-black text-xs uppercase tracking-widest disabled:opacity-30 enabled:hover:bg-gray-50 transition-all">Anterior</button>
      <div class="px-6 py-3 flex items-center font-black text-primary-600 text-xs">
        PÁGINA {{ page() }}
      </div>
      <button [disabled]="reviews().length < pageSize()" (click)="page.set(page() + 1); loadReviews()"
              class="px-6 py-3 rounded-xl font-black text-xs uppercase tracking-widest disabled:opacity-30 enabled:hover:bg-gray-50 transition-all">Próxima</button>
    </div>
  </footer>
</div>

// src/UI/Web/React/src/features/reviews/Reviews.tsx
import { useState, useEffect } from 'react';
import { customerReviewService } from '../../api/services';
import { Star, Search, Filter, Trash2, CheckCircle, XCircle, ChevronLeft, ChevronRight } from 'lucide-react';

export default function Reviews() {
  const [reviews, setReviews] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [totalCount, setTotalCount] = useState(0);
  const [page, setPage] = useState(1);
  const pageSize = 8;

  // Filters
  const [productName, setProductName] = useState('');
  const [minRating, setMinRating] = useState<number | undefined>(undefined);
  const [isApproved, setIsApproved] = useState<boolean | undefined>(undefined);

  const loadReviews = async () => {
    setLoading(true);
    try {
      const data = await customerReviewService.getReviews(page, pageSize, productName, minRating, isApproved);
      setReviews(data.items);
      setTotalCount(data.totalCount);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadReviews();
  }, [page, isApproved, minRating]);

  const handleApprove = async (id: string, approve: boolean) => {
    await customerReviewService.approve(id, approve);
    loadReviews();
  };

  const handleDelete = async (id: string) => {
    if (window.confirm('Tem certeza que deseja excluir esta avaliação?')) {
      await customerReviewService.delete(id);
      loadReviews();
    }
  };

  return (
    <div className="p-10 max-w-7xl mx-auto space-y-10 animate-in fade-in duration-700">
      {/* Header */}
      <header className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6">
        <div>
          <h1 className="text-6xl font-black text-gray-900 tracking-tighter">Customer Reviews</h1>
          <p className="text-gray-500 mt-4 font-medium text-xl">Gerenciamento e moderação de avaliações (MongoDB).</p>
        </div>
        <div className="flex gap-4">
          <div className="bg-white p-2 rounded-2xl shadow-sm border border-gray-100 flex gap-2">
            <button 
              onClick={() => setIsApproved(undefined)}
              className={`px-6 py-2 rounded-xl font-bold transition-all ${isApproved === undefined ? 'bg-gray-900 text-white' : 'text-gray-500 hover:bg-gray-50'}`}
            >
              Todos
            </button>
            <button 
              onClick={() => setIsApproved(true)}
              className={`px-6 py-2 rounded-xl font-bold transition-all ${isApproved === true ? 'bg-green-600 text-white' : 'text-gray-500 hover:bg-gray-50'}`}
            >
              Aprovados
            </button>
            <button 
              onClick={() => setIsApproved(false)}
              className={`px-6 py-2 rounded-xl font-bold transition-all ${isApproved === false ? 'bg-amber-500 text-white' : 'text-gray-500 hover:bg-gray-50'}`}
            >
              Pendentes
            </button>
          </div>
        </div>
      </header>

      {/* Filters */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="relative group">
          <input 
            type="text" 
            value={productName}
            onChange={(e) => setProductName(e.target.value)}
            onKeyUp={(e) => e.key === 'Enter' && loadReviews()}
            placeholder="Buscar por produto..."
            className="w-full pl-14 pr-6 py-5 bg-white border-none rounded-3xl shadow-xl shadow-gray-200/50 font-bold text-gray-700 focus:ring-2 focus:ring-primary-500 transition-all outline-none"
          />
          <Search className="absolute left-6 top-1/2 -translate-y-1/2 text-gray-300 group-focus-within:text-primary-500 transition-colors" size={24} />
        </div>

        <div className="relative group">
          <select 
            value={minRating || ''}
            onChange={(e) => setMinRating(e.target.value ? Number(e.target.value) : undefined)}
            className="w-full pl-14 pr-6 py-5 bg-white border-none rounded-3xl shadow-xl shadow-gray-200/50 font-bold text-gray-700 focus:ring-2 focus:ring-primary-500 transition-all outline-none appearance-none"
          >
            <option value="">Mínimo de Estrelas</option>
            <option value="1">1+ Estrela</option>
            <option value="2">2+ Estrelas</option>
            <option value="3">3+ Estrelas</option>
            <option value="4">4+ Estrelas</option>
            <option value="5">5 Estrelas</option>
          </select>
          <Star className="absolute left-6 top-1/2 -translate-y-1/2 text-gray-300 group-focus-within:text-primary-500 transition-colors" size={24} />
        </div>
      </div>

      {/* Content */}
      {loading ? (
        <div className="flex flex-col items-center justify-center py-32 space-y-6">
          <div className="w-16 h-16 border-4 border-primary-100 border-t-primary-600 rounded-full animate-spin" />
          <p className="text-gray-400 font-black animate-pulse">CARREGANDO AVALIAÇÕES...</p>
        </div>
      ) : reviews.length === 0 ? (
        <div className="bg-white rounded-[3rem] p-32 text-center shadow-2xl shadow-gray-100 border border-gray-50">
          <div className="text-8xl mb-8">📭</div>
          <h3 className="text-3xl font-black text-gray-900">Nenhuma avaliação encontrada</h3>
          <p className="text-gray-400 mt-4 font-medium">Tente ajustar seus filtros para encontrar o que procura.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
          {reviews.map((review) => (
            <div key={review.id} className="bg-white p-8 rounded-[2.5rem] shadow-xl hover:shadow-2xl transition-all border border-gray-50 flex flex-col justify-between group">
              <div>
                <div className="flex justify-between items-start mb-6">
                  <div className="flex gap-0.5">
                    {[...Array(5)].map((_, i) => (
                      <Star 
                        key={i} 
                        size={18} 
                        fill={i < review.rating ? '#fbbf24' : 'transparent'} 
                        className={i < review.rating ? 'text-amber-400' : 'text-gray-100'} 
                      />
                    ))}
                  </div>
                  {review.isVerifiedPurchase && (
                    <span className="bg-green-50 text-green-600 text-[10px] font-black px-3 py-1 rounded-full uppercase tracking-widest">
                      Verificado
                    </span>
                  )}
                </div>

                <h4 className="text-xl font-black text-gray-900 mb-2 leading-tight group-hover:text-primary-600 transition-colors">{review.title}</h4>
                <p className="text-gray-500 text-sm font-medium line-clamp-3 mb-6">{review.comment}</p>
              </div>

              <div className="space-y-6">
                <div className="flex items-center gap-4 py-4 border-t border-gray-50">
                  <div className="w-10 h-10 bg-primary-50 rounded-xl flex items-center justify-center text-primary-600 font-black text-xs uppercase">
                    {review.customerName[0]}
                  </div>
                  <div className="min-w-0">
                    <p className="text-sm font-black text-gray-900 truncate tracking-tight">{review.customerName}</p>
                    <p className="text-[10px] text-gray-400 font-bold uppercase truncate tracking-widest">{review.productName}</p>
                  </div>
                </div>

                <div className="flex gap-3">
                  {!review.isApproved ? (
                    <button 
                      onClick={() => handleApprove(review.id, true)}
                      className="flex-1 py-3 bg-green-50 text-green-600 rounded-xl font-black text-[10px] uppercase tracking-widest hover:bg-green-600 hover:text-white transition-all shadow-sm flex items-center justify-center gap-2"
                    >
                      <CheckCircle size={14} /> Aprovar
                    </button>
                  ) : (
                    <button 
                      onClick={() => handleApprove(review.id, false)}
                      className="flex-1 py-3 bg-amber-50 text-amber-600 rounded-xl font-black text-[10px] uppercase tracking-widest hover:bg-amber-500 hover:text-white transition-all shadow-sm flex items-center justify-center gap-2"
                    >
                      <XCircle size={14} /> Rejeitar
                    </button>
                  )}
                  <button 
                    onClick={() => handleDelete(review.id)}
                    className="p-3 bg-rose-50 text-rose-600 rounded-xl font-black hover:bg-rose-600 hover:text-white transition-all shadow-sm"
                  >
                    <Trash2 size={18} />
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Pagination */}
      {!loading && totalCount > pageSize && (
        <footer className="flex justify-center pt-10">
          <div className="bg-white p-2 rounded-2xl shadow-xl border border-gray-50 flex gap-2">
            <button 
              disabled={page === 1} 
              onClick={() => setPage(page - 1)}
              className="px-6 py-3 rounded-xl font-black text-xs uppercase tracking-widest disabled:opacity-30 enabled:hover:bg-gray-50 transition-all flex items-center gap-2"
            >
              <ChevronLeft size={16} /> Anterior
            </button>
            <div className="px-6 py-3 flex items-center font-black text-primary-600 text-xs uppercase tracking-tighter">
              Página {page}
            </div>
            <button 
              disabled={reviews.length < pageSize} 
              onClick={() => setPage(page + 1)}
              className="px-6 py-3 rounded-xl font-black text-xs uppercase tracking-widest disabled:opacity-30 enabled:hover:bg-gray-50 transition-all flex items-center gap-2"
            >
              Próxima <ChevronRight size={16} />
            </button>
          </div>
        </footer>
      )}
    </div>
  );
}
