// src/UI/Web/Angular/src/app/shared/components/layout/main-layout.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, RouterLinkActive, Router, RouterOutlet } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-main-layout',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive, RouterOutlet],
  templateUrl: './main-layout.component.html'
})
export class MainLayoutComponent {
  private authService = inject(AuthService);
  private router = inject(Router);

  user = this.authService.currentUser;

  isAdmin = () => this.user()?.email?.toLowerCase() === 'admin@projecttemplate.com';
  userInitial = () => this.isAdmin() ? 'S' : (this.user()?.firstName?.[0] || this.user()?.email?.[0] || 'U').toUpperCase();
  userName = () => this.isAdmin() ? 'System Administrator' : (this.user()?.firstName ? `${this.user()?.firstName} ${this.user()?.lastName}` : 'Usuário');

  menuItems = [
    { name: 'Dashboard', path: '/dashboard', icon: '📊' },
    { name: 'Produtos', path: '/products', icon: '📦' },
    { name: 'Pedidos', path: '/orders', icon: '🛍️' },
    { name: 'Auditoria', path: '/audit', icon: '🛡️' },
    { name: 'Documentos', path: '/documents', icon: '📄' },
    { name: 'Avaliações', path: '/reviews', icon: '⭐' },
  ];

  handleLogout() {
    this.authService.logout();
    this.router.navigate(['/login']);
  }
}

<div class="flex h-screen bg-gray-100 overflow-hidden font-sans">
  <!-- Sidebar -->
  <div class="w-72 bg-white shadow-2xl relative flex flex-col z-20">
    <div class="p-10 border-b border-gray-50 flex items-center gap-4">
      <div class="w-12 h-12 bg-primary-600 rounded-[1.25rem] flex items-center justify-center text-white font-black text-2xl shadow-xl shadow-primary-600/20">
        ET
      </div>
      <div class="flex flex-col">
        <span class="font-black text-2xl text-gray-900 tracking-tighter">Enterprise</span>
        <span class="text-[10px] font-bold text-primary-600 uppercase tracking-[0.3em] -mt-1">Angular Edition</span>
      </div>
    </div>

    <nav class="mt-10 px-6 flex-1 space-y-3">
      @for (item of menuItems; track item.path) {
        <a
          [routerLink]="item.path"
          routerLinkActive="bg-primary-600 text-white shadow-lg shadow-primary-600/30"
          [routerLinkActiveOptions]="{exact: true}"
          class="flex items-center gap-4 px-6 py-4 rounded-2xl transition-all duration-300 group text-gray-400 hover:bg-gray-50 hover:text-gray-900"
        >
          <span class="text-xl group-hover:scale-110 transition-transform">{{ item.icon }}</span>
          <span class="font-black text-xs uppercase tracking-widest">{{ item.name }}</span>
        </a>
      }
    </nav>

    <!-- User Section -->
    <div class="p-8 border-t border-gray-100 flex flex-col gap-6 bg-gray-50/30">
      <div class="flex items-center gap-4 group cursor-default">
        <div class="w-14 h-14 bg-gradient-to-br from-primary-500 to-primary-700 rounded-2xl flex items-center justify-center text-white font-black text-2xl shadow-xl shadow-primary-200 group-hover:scale-110 transition-transform">
          {{ userInitial() }}
        </div>
        <div class="flex-1 min-w-0">
          <p class="text-sm font-black text-gray-900 truncate tracking-tight">
            {{ userName() }}
          </p>
          <p class="text-[10px] text-gray-400 font-bold truncate uppercase tracking-widest">{{ user()?.email }}</p>
        </div>
      </div>
      <button
        (click)="handleLogout()"
        class="w-full flex items-center justify-center gap-3 px-6 py-4 bg-white border border-red-100 text-red-500 rounded-2xl hover:bg-red-600 hover:text-white hover:border-red-600 transition-all duration-300 text-[11px] font-black uppercase tracking-widest active:scale-95 shadow-sm hover:shadow-xl hover:shadow-red-600/20 group/logout"
      >
        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" class="group-hover/logout:translate-x-1 transition-transform">
          <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
          <polyline points="16 17 21 12 16 7"></polyline>
          <line x1="21" y1="12" x2="9" y2="12"></line>
        </svg>
        Sair da Conta
      </button>
    </div>
  </div>

  <!-- Main Content Area -->
  <div class="flex-1 overflow-auto bg-gray-50/50 relative">
    <div class="absolute inset-0 bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:24px_24px] [mask-image:radial-gradient(ellipse_50%_50%_at_50%_50%,#000_70%,transparent_100%)] opacity-40 pointer-events-none"></div>
    <main class="relative z-10 min-h-full">
      <div class="p-10">
        <router-outlet />
      </div>
    </main>
  </div>
</div>

// src/UI/Web/React/src/layouts/MainLayout.tsx
import React from 'react';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import { useAuthStore } from '../store/useAuthStore';

export default function MainLayout({ children }: { children: React.ReactNode }) {
  const logout = useAuthStore((state) => state.logout);
  const user = useAuthStore((state) => state.user);
  const navigate = useNavigate();
  const location = useLocation();

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  const menuItems = [
    { name: 'Dashboard', path: '/dashboard', icon: '📊' },
    { name: 'Produtos', path: '/products', icon: '📦' },
    { name: 'Pedidos', path: '/orders', icon: '🛍️' },
    { name: 'Auditoria', path: '/audit', icon: '🛡️' },
    { name: 'Documentos', path: '/documents', icon: '📄' },
    { name: 'Avaliações', path: '/reviews', icon: '⭐' },
  ];

  const userEmail = user?.email || 'admin@projecttemplate.com';
  const isAdmin = userEmail.toLowerCase() === 'admin@projecttemplate.com';
  const userInitial = isAdmin ? 'S' : (user?.firstName?.[0] || user?.email?.[0] || 'U').toUpperCase();
  const userName = isAdmin ? 'System Administrator' : (user?.firstName ? `${user.firstName} ${user.lastName}` : 'Usuário');

  return (
    <div className="flex h-screen bg-gray-100 overflow-hidden font-sans">
      {/* Sidebar */}
      <div className="w-72 bg-white shadow-2xl relative flex flex-col z-20">
        <div className="p-10 border-b border-gray-50 flex items-center gap-4">
          <div className="w-12 h-12 bg-primary-600 rounded-[1.25rem] flex items-center justify-center text-white font-black text-2xl shadow-xl shadow-primary-600/20">
            ET
          </div>
          <div className="flex flex-col">
            <span className="font-black text-2xl text-gray-900 tracking-tighter">Enterprise</span>
            <span className="text-[10px] font-bold text-primary-600 uppercase tracking-[0.3em] -mt-1">React Edition</span>
          </div>
        </div>

        <nav className="mt-10 px-6 space-y-3 flex-1">
          {menuItems.map((item) => (
            <Link
              key={item.path}
              to={item.path}
              className={`flex items-center gap-4 px-6 py-4 rounded-2xl transition-all duration-300 group ${
                location.pathname === item.path
                  ? 'bg-primary-600 text-white shadow-lg shadow-primary-600/30'
                  : 'text-gray-400 hover:bg-gray-50 hover:text-gray-900'
              }`}
            >
              <span className="text-xl group-hover:scale-110 transition-transform">{item.icon}</span>
              <span className="font-black text-xs uppercase tracking-widest">{item.name}</span>
            </Link>
          ))}
        </nav>

        {/* User Section */}
        <div className="p-8 border-t border-gray-100 flex flex-col gap-6 bg-gray-50/30">
          <div className="flex items-center gap-4 group cursor-default">
            <div className="w-14 h-14 bg-gradient-to-br from-primary-500 to-primary-700 rounded-2xl flex items-center justify-center text-white font-black text-2xl shadow-xl shadow-primary-200 group-hover:scale-110 transition-transform">
              {userInitial}
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-black text-gray-900 truncate tracking-tight">{userName}</p>
              <p className="text-[10px] text-gray-400 font-bold truncate uppercase tracking-widest">{user?.email || 'admin@projecttemplate.com'}</p>
            </div>
          </div>
          <button
            onClick={handleLogout}
            className="w-full flex items-center justify-center gap-3 px-6 py-4 bg-white border border-red-100 text-red-500 rounded-2xl hover:bg-red-600 hover:text-white hover:border-red-600 transition-all duration-300 text-[11px] font-black uppercase tracking-widest active:scale-95 shadow-sm hover:shadow-xl hover:shadow-red-600/20 group/logout"
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" className="group-hover/logout:translate-x-1 transition-transform">
              <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
              <polyline points="16 17 21 12 16 7"></polyline>
              <line x1="21" y1="12" x2="9" y2="12"></line>
            </svg>
            Sair da Conta
          </button>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 overflow-auto bg-gray-50/50 relative">
        <div className="absolute inset-0 bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:24px_24px] [mask-image:radial-gradient(ellipse_50%_50%_at_50%_50%,#000_70%,transparent_100%)] opacity-40 pointer-events-none"></div>
        <main className="relative z-10 min-h-full">
          <div className="p-10">
            {children}
          </div>
        </main>
      </div>
    </div>
  );
}
