// src/UI/Web/Vue/src/components/Dropdown.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';

interface Option {
  label: string;
  value: any;
}

const props = defineProps<{
  options: Option[];
  modelValue: any;
  placeholder?: string;
  variant?: 'filter' | 'form';
  className?: string;
}>();

const emit = defineEmits(['update:modelValue']);

const isOpen = ref(false);
const dropdownRef = ref<HTMLElement | null>(null);

const toggle = () => {
  isOpen.value = !isOpen.value;
};

const select = (option: Option) => {
  emit('update:modelValue', option.value);
  isOpen.value = false;
};

const handleClickOutside = (event: MouseEvent) => {
  if (dropdownRef.value && !dropdownRef.value.contains(event.target as Node)) {
    isOpen.value = false;
  }
};

onMounted(() => document.addEventListener('mousedown', handleClickOutside));
onUnmounted(() => document.removeEventListener('mousedown', handleClickOutside));

const selectedOption = () => props.options.find(opt => opt.value === props.modelValue);

const paddingClass = props.variant === 'form' ? 'py-3' : 'py-5';
const roundedClass = props.variant === 'form' ? 'rounded-2xl' : 'rounded-3xl';
const bgClass = props.variant === 'form' ? 'bg-gray-50' : 'bg-white';
const shadowClass = props.variant === 'form' ? '' : 'shadow-xl shadow-gray-100/50';
</script>

<template>
  <div ref="dropdownRef" class="relative" :class="className">
    <button
      type="button"
      @click="toggle"
      class="w-full pl-8 pr-12 border-none outline-none font-black text-xs uppercase tracking-widest text-gray-900 flex justify-between items-center hover:bg-gray-50 transition-all active:scale-[0.98]"
      :class="[paddingClass, bgClass, roundedClass, shadowClass]"
    >
      <span class="truncate">{{ selectedOption() ? selectedOption()?.label : (placeholder || 'Selecionar...') }}</span>
      <svg 
        class="w-5 h-5 text-gray-300 transition-transform duration-300"
        :class="{ 'rotate-180': isOpen }"
        fill="none" 
        stroke="currentColor" 
        viewBox="0 0 24 24"
      >
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M19 9l-7 7-7-7" />
      </svg>
    </button>

    <Transition
      enter-active-class="transition duration-200 ease-out"
      enter-from-class="transform scale-95 opacity-0"
      enter-to-class="transform scale-100 opacity-100"
      leave-active-class="transition duration-150 ease-in"
      leave-from-class="transform scale-100 opacity-100"
      leave-to-class="transform scale-95 opacity-0"
    >
      <div v-if="isOpen" class="absolute z-50 w-full mt-3 bg-white border border-gray-50 rounded-[2rem] shadow-2xl shadow-gray-200/50 py-3 overflow-hidden">
        <div class="max-h-60 overflow-y-auto">
          <button
            v-for="option in options"
            :key="option.value"
            type="button"
            @click="select(option)"
            class="w-full text-left px-8 py-4 text-[10px] font-black uppercase tracking-widest transition-colors"
            :class="modelValue === option.value ? 'bg-primary-50 text-primary-600' : 'text-gray-500 hover:bg-gray-50'"
          >
            {{ option.label }}
          </button>
        </div>
      </div>
    </Transition>
  </div>
</template>

// src/UI/Web/React/src/components/Dropdown.tsx
import { useState, useRef, useEffect } from 'react';

interface Option {
  label: string;
  value: string;
}

interface DropdownProps {
  options: Option[];
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
  className?: string;
  variant?: 'filter' | 'form';
}

export default function Dropdown({ options, value, onChange, placeholder = 'Selecionar...', className = '', variant = 'filter' }: DropdownProps) {
  const [isOpen, setIsOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  const selectedOption = options.find(opt => opt.value === value);

  const paddingClass = variant === 'filter' ? 'py-5' : 'py-3';
  const roundedClass = variant === 'filter' ? 'rounded-3xl' : 'rounded-2xl';
  const bgClass = variant === 'filter' ? 'bg-white' : 'bg-gray-50';
  const shadowClass = variant === 'filter' ? 'shadow-xl shadow-gray-100/50' : '';

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  return (
    <div ref={dropdownRef} className={`relative ${className}`}>
      <button
        type="button"
        onClick={() => setIsOpen(!isOpen)}
        className={`w-full pl-8 pr-12 ${paddingClass} ${bgClass} border-none ${roundedClass} ${shadowClass} outline-none font-black text-xs uppercase tracking-widest text-gray-900 flex justify-between items-center hover:bg-gray-50 transition-all active:scale-[0.98]`}
      >
        <span className="truncate">{selectedOption ? selectedOption.label : placeholder}</span>
        <svg 
          className={`w-5 h-5 text-gray-300 transition-transform duration-300 ${isOpen ? 'rotate-180' : ''}`} 
          fill="none" 
          stroke="currentColor" 
          viewBox="0 0 24 24"
        >
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M19 9l-7 7-7-7" />
        </svg>
      </button>

      {isOpen && (
        <div className="absolute z-50 w-full mt-3 bg-white border border-gray-50 rounded-[2rem] shadow-2xl shadow-gray-200/50 py-3 overflow-hidden animate-in fade-in zoom-in-95 duration-200">
          <div className="max-h-60 overflow-y-auto">
            {options.map((option) => (
              <button
                key={option.value}
                type="button"
                onClick={() => {
                  onChange(option.value);
                  setIsOpen(false);
                }}
                className={`w-full text-left px-8 py-4 text-[10px] font-black uppercase tracking-widest transition-colors ${
                  value === option.value 
                  ? 'bg-primary-50 text-primary-600' 
                  : 'text-gray-500 hover:bg-gray-50'
                }`}
              >
                {option.label}
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
