// src/UI/Web/Angular/src/app/shared/components/pagination/pagination.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-pagination',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './pagination.component.html'
})
export class PaginationComponent {
  @Input() page = 1;
  @Input() pageSize = 10;
  @Input() totalPages = 1;
  @Input() totalItems = 0;
  @Output() pageChange = new EventEmitter<number>();
  @Output() pageSizeChange = new EventEmitter<number>();

  onPageChange(newPage: number) {
    if (newPage >= 1 && (this.totalPages === 0 || newPage <= this.totalPages)) {
      this.pageChange.emit(newPage);
    }
  }

  onPageSizeChange(newSize: number) {
    this.pageSizeChange.emit(Number(newSize));
  }
}

<div class="bg-gray-50 px-10 py-6 flex justify-between items-center border-t border-gray-100">
  <div class="flex items-center gap-10">
    <div class="flex items-center gap-2 text-sm font-bold text-gray-500">
      <span>Página</span>
      <span class="text-gray-900">{{ page }}</span>
      <span>de</span>
      <span class="text-gray-900">{{ totalPages || 1 }}</span>
    </div>

    <div class="flex items-center gap-3">
      <span class="text-[10px] font-black uppercase tracking-widest text-gray-400">Itens por página:</span>
      <select 
        [ngModel]="pageSize" 
        (ngModelChange)="onPageSizeChange($event)"
        class="bg-white border border-gray-200 rounded-xl px-4 py-2 text-xs font-black text-gray-900 focus:outline-none focus:ring-2 focus:ring-primary-600 transition-all cursor-pointer shadow-sm"
      >
        <option [value]="5">5</option>
        <option [value]="10">10</option>
        <option [value]="20">20</option>
        <option [value]="50">50</option>
        <option [value]="100">100</option>
      </select>
    </div>
  </div>

  <div class="flex gap-3">
    <button 
      (click)="onPageChange(page - 1)"
      [disabled]="page === 1"
      class="px-6 py-3 bg-white border border-gray-200 rounded-xl font-black text-xs uppercase tracking-widest hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-sm active:scale-95"
    >
      Anterior
    </button>
    <button 
      (click)="onPageChange(page + 1)"
      [disabled]="page === totalPages || totalPages === 0"
      class="px-6 py-3 bg-primary-600 text-white rounded-xl font-black text-xs uppercase tracking-widest hover:bg-primary-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-lg shadow-primary-600/20 active:scale-95"
    >
      Próxima
    </button>
  </div>
</div>

// src/UI/Web/React/src/components/Pagination.tsx
import React from 'react';

interface PaginationProps {
  currentPage: number;
  totalPages: number;
  pageSize: number;
  onPageChange: (page: number) => void;
  onPageSizeChange: (pageSize: number) => void;
}

const Pagination: React.FC<PaginationProps> = ({
  currentPage,
  totalPages,
  pageSize,
  onPageChange,
  onPageSizeChange,
}) => {
  return (
    <div className="bg-gray-50 px-10 py-6 flex justify-between items-center border-t border-gray-100">
      <div className="flex flex-col sm:flex-row sm:items-center gap-4 sm:gap-10">
        <p className="text-sm text-gray-500 font-bold">
          Página <span className="text-gray-900">{currentPage}</span> de <span className="text-gray-900">{totalPages || 1}</span>
        </p>
        
        <div className="flex items-center gap-3">
          <span className="text-[10px] font-black uppercase tracking-widest text-gray-400">Itens por página:</span>
          <select 
            value={pageSize}
            onChange={(e) => onPageSizeChange(Number(e.target.value))}
            className="bg-white border border-gray-200 rounded-xl px-4 py-2 text-xs font-black text-gray-900 focus:outline-none focus:ring-2 focus:ring-primary-600 transition-all cursor-pointer shadow-sm"
          >
            {[5, 10, 20, 50, 100].map(size => (
              <option key={size} value={size}>{size}</option>
            ))}
          </select>
        </div>
      </div>

      <div className="flex gap-3">
        <button
          onClick={() => onPageChange(Math.max(1, currentPage - 1))}
          disabled={currentPage === 1}
          className="px-6 py-3 bg-white border border-gray-200 rounded-xl font-black text-xs uppercase tracking-widest hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-sm active:scale-95"
        >
          Anterior
        </button>
        <button
          onClick={() => onPageChange(Math.min(totalPages, currentPage + 1))}
          disabled={currentPage === totalPages || totalPages === 0}
          className="px-6 py-3 bg-primary-600 text-white rounded-xl font-black text-xs uppercase tracking-widest hover:bg-primary-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-lg shadow-primary-600/20 active:scale-95"
        >
          Próxima
        </button>
      </div>
    </div>
  );
};

export default Pagination;
