// src/UI/Web/Angular/src/app/features/products/pages/products.component.ts
import { Component, inject, signal, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ProductService } from '../../../core/services/data-services';
import { ProductResponseDto } from '../../../shared/models/models';
import { ModalComponent } from '../../../shared/components/modal/modal.component';
import { PaginationComponent } from '../../../shared/components/pagination/pagination.component';
import { Subject, debounceTime, distinctUntilChanged, takeUntil } from 'rxjs';

@Component({
  selector: 'app-products',
  standalone: true,
  imports: [CommonModule, FormsModule, ModalComponent, PaginationComponent],
  templateUrl: './products.component.html'
})
export class ProductsComponent implements OnInit, OnDestroy {
  private productService = inject(ProductService);
  private destroy$ = new Subject<void>();
  private searchSubject = new Subject<string>();
  
  products = signal<ProductResponseDto[]>([]);
  loading = signal(true);
  
  // Filters
  searchTerm = '';
  isActive: boolean | undefined = undefined;
  
  // Pagination
  page = 1;
  pageSize = 10;
  totalItems = 0;
  totalPages = 0;

  // Modal
  showModal = false;
  modalTitle = 'Novo Produto';
  editingProduct: any = null;
  formData = {
    name: '',
    category: '',
    price: 0,
    stock: 0,
    isActive: true
  };

  ngOnInit() {
    this.loadProducts();

    // Debounced search logic
    this.searchSubject.pipe(
      debounceTime(400),
      distinctUntilChanged(),
      takeUntil(this.destroy$)
    ).subscribe(() => {
      this.onSearch();
    });
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  loadProducts() {
    this.loading.set(true);
    this.productService.getProducts(this.page, this.pageSize, this.searchTerm, this.isActive).subscribe({
      next: (res) => {
        this.products.set(res.items);
        this.totalItems = res.totalCount;
        this.totalPages = res.totalPages;
        this.loading.set(false);
      },
      error: () => this.loading.set(false)
    });
  }

  onSearchChange(value: string) {
    this.searchTerm = value;
    this.searchSubject.next(value);
  }

  onSearch() {
    this.page = 1;
    this.loadProducts();
  }

  onStatusFilter(val: any) {
    this.isActive = val;
    this.page = 1;
    this.loadProducts();
  }

  onPageChange(newPage: number) {
    this.page = newPage;
    this.loadProducts();
  }

  onPageSizeChange(newSize: number) {
    this.pageSize = newSize;
    this.page = 1;
    this.loadProducts();
  }

  exportExcel() {
    this.productService.exportToExcel(this.searchTerm, this.isActive).subscribe({
      next: (blob) => {
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `produtos-${new Date().getTime()}.xlsx`;
        a.click();
        window.URL.revokeObjectURL(url);
      },
      error: () => alert('Erro ao exportar produtos')
    });
  }

  openNew() {
    this.editingProduct = null;
    this.modalTitle = 'Novo Produto';
    this.formData = { name: '', category: '', price: 0, stock: 0, isActive: true };
    this.showModal = true;
  }

  openEdit(product: ProductResponseDto) {
    this.editingProduct = product;
    this.modalTitle = 'Editar Produto';
    this.formData = { ...product };
    this.showModal = true;
  }

  save() {
    const obs = this.editingProduct 
      ? this.productService.updateProduct(this.editingProduct.id, this.formData)
      : this.productService.createProduct(this.formData);

    obs.subscribe({
      next: () => {
        this.showModal = false;
        this.loadProducts();
      },
      error: (err) => alert('Erro ao salvar produto: ' + (err.error?.message || 'Erro desconhecido'))
    });
  }

  deleteProduct(id: string) {
    if (confirm('Deseja excluir este produto?')) {
      this.productService.deleteProduct(id).subscribe({
        next: () => this.loadProducts(),
        error: () => alert('Erro ao excluir produto')
      });
    }
  }
}

<div class="p-12 max-w-[1600px] mx-auto animate-in fade-in duration-700">
  <header class="flex justify-between items-end mb-12">
    <div>
      <h1 class="text-5xl font-black text-gray-900 tracking-tighter">Produtos</h1>
      <p class="text-gray-500 mt-3 font-medium text-lg">Catálogo completo de itens.</p>
    </div>
    <div class="flex gap-4">
      <button 
        (click)="exportExcel()"
        class="bg-white border-2 border-gray-100 hover:border-primary-100 text-gray-600 font-black px-8 py-4 rounded-2xl shadow-xl shadow-gray-100/20 transition-all active:scale-95 flex items-center gap-2"
      >
        📥 Exportar
      </button>
      <button 
        (click)="openNew()"
        class="bg-primary-600 hover:bg-primary-700 text-white font-black px-8 py-4 rounded-2xl shadow-lg shadow-primary-600/20 transition-all active:scale-95"
      >
        + Novo Produto
      </button>
    </div>
  </header>

  <!-- Filter Bar -->
  <div class="flex gap-6 items-center mb-10">
    <div class="flex-1 relative group">
      <div class="absolute inset-y-0 left-6 flex items-center pointer-events-none">
        <svg class="w-5 h-5 text-gray-400 group-focus-within:text-primary-600 transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
        </svg>
      </div>
      <input 
        type="text"
        placeholder="Buscar por nome ou categoria..."
        class="w-full pl-16 pr-8 py-5 bg-white border-none rounded-3xl shadow-xl shadow-gray-100/50 focus:ring-2 focus:ring-primary-600/20 outline-none transition-all font-bold text-gray-900 placeholder:text-gray-300"
        [ngModel]="searchTerm"
        (ngModelChange)="onSearchChange($event)"
      />
    </div>
    
    <div class="flex bg-white p-2 rounded-[2rem] shadow-xl shadow-gray-100/50 gap-1">
      <button
        (click)="onStatusFilter(undefined)"
        [class]="'px-8 py-3 rounded-2xl font-black text-xs uppercase tracking-widest transition-all ' + (isActive === undefined ? 'bg-gray-900 text-white shadow-lg' : 'text-gray-400 hover:bg-gray-50')"
      >
        Todos
      </button>
      <button
        (click)="onStatusFilter(true)"
        [class]="'px-8 py-3 rounded-2xl font-black text-xs uppercase tracking-widest transition-all ' + (isActive === true ? 'bg-gray-900 text-white shadow-lg' : 'text-gray-400 hover:bg-gray-50')"
      >
        Ativos
      </button>
      <button
        (click)="onStatusFilter(false)"
        [class]="'px-8 py-3 rounded-2xl font-black text-xs uppercase tracking-widest transition-all ' + (isActive === false ? 'bg-gray-900 text-white shadow-lg' : 'text-gray-400 hover:bg-gray-50')"
      >
        Inativos
      </button>
    </div>
  </div>

  @if (loading()) {
    <div class="flex justify-center py-40 bg-white rounded-[3rem] shadow-xl shadow-gray-100/50">
      <div class="w-16 h-16 border-8 border-primary-600 border-t-transparent rounded-full animate-spin"></div>
    </div>
  } @else {
    <div class="bg-white rounded-[3rem] shadow-2xl shadow-gray-200/40 border border-gray-50 overflow-hidden">
      <table class="w-full text-left">
        <thead>
          <tr class="bg-gray-50/50">
            <th class="px-10 py-8 text-[10px] font-black text-gray-400 uppercase tracking-[0.2em]">Produto</th>
            <th class="px-10 py-8 text-[10px] font-black text-gray-400 uppercase tracking-[0.2em]">Categoria</th>
            <th class="px-10 py-8 text-[10px] font-black text-gray-400 uppercase tracking-[0.2em]">Preço</th>
            <th class="px-10 py-8 text-[10px] font-black text-gray-400 uppercase tracking-[0.2em]">Estoque</th>
            <th class="px-10 py-8 text-[10px] font-black text-gray-400 uppercase tracking-[0.2em]">Status</th>
            <th class="px-10 py-8 text-[10px] font-black text-gray-400 uppercase tracking-[0.2em] text-right">Ações</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-50">
          @for (product of products(); track product.id) {
            <tr class="hover:bg-gray-50/50 transition-colors group">
              <td class="px-10 py-8">
                <div class="flex items-center gap-6">
                  <div class="w-14 h-14 bg-gray-50 rounded-2xl flex items-center justify-center text-2xl group-hover:scale-110 transition-transform">
                    📦
                  </div>
                  <span class="font-black text-gray-900 text-lg tracking-tight">{{ product.name }}</span>
                </div>
              </td>
              <td class="px-10 py-8">
                <span class="px-4 py-2 bg-gray-50 rounded-xl text-gray-500 font-bold text-xs uppercase tracking-wider">
                  {{ product.category }}
                </span>
              </td>
              <td class="px-10 py-8">
                <span class="font-black text-primary-600 text-lg">R$ {{ product.price | number:'1.2-2' }}</span>
              </td>
              <td class="px-10 py-8">
                <div class="flex items-baseline gap-1">
                  <span class="font-black text-gray-900 text-lg">{{ product.stock }}</span>
                  <span class="text-[10px] font-bold text-gray-300 uppercase tracking-widest">unid</span>
                </div>
              </td>
              <td class="px-10 py-8">
                <span [class]="'px-4 py-2 rounded-xl font-black text-[10px] uppercase tracking-widest ' + (product.isActive ? 'bg-emerald-50 text-emerald-600' : 'bg-red-50 text-red-600')">
                  {{ product.isActive ? 'Ativo' : 'Inativo' }}
                </span>
              </td>
              <td class="px-10 py-8 text-right">
                <div class="flex justify-end gap-2">
                  <button (click)="openEdit(product)" class="w-10 h-10 flex items-center justify-center bg-gray-50 hover:bg-primary-50 rounded-xl text-primary-600 transition-all active:scale-90" title="Editar">
                    ✏️
                  </button>
                  <button (click)="deleteProduct(product.id)" class="w-10 h-10 flex items-center justify-center bg-gray-50 hover:bg-red-50 rounded-xl text-red-600 transition-all active:scale-90" title="Excluir">
                    🗑️
                  </button>
                </div>
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>

    <app-pagination 
      [page]="page" 
      [pageSize]="pageSize"
      [totalPages]="totalPages" 
      [totalItems]="totalItems" 
      (pageChange)="onPageChange($event)"
      (pageSizeChange)="onPageSizeChange($event)"
    ></app-pagination>
  }
</div>

<!-- Product Modal -->
<app-modal [show]="showModal" [title]="modalTitle" (close)="showModal = false">
  <form (submit)="save()" class="space-y-8">
    <div class="space-y-3">
      <label class="text-[10px] font-black uppercase tracking-[0.2em] text-gray-400 ml-4">Nome do Produto</label>
      <input 
        type="text" 
        [(ngModel)]="formData.name" 
        name="name"
        class="w-full px-8 py-5 bg-gray-50 border-none rounded-3xl outline-none font-bold text-gray-900 focus:ring-2 focus:ring-primary-600/10 transition-all"
        placeholder="Ex: Teclado Mecânico"
        required
      />
    </div>

    <div class="grid grid-cols-2 gap-6">
      <div class="space-y-3">
        <label class="text-[10px] font-black uppercase tracking-[0.2em] text-gray-400 ml-4">Categoria</label>
        <input 
          type="text" 
          [(ngModel)]="formData.category" 
          name="category"
          class="w-full px-8 py-5 bg-gray-50 border-none rounded-3xl outline-none font-bold text-gray-900 focus:ring-2 focus:ring-primary-600/10 transition-all"
          placeholder="Ex: Hardware"
          required
        />
      </div>
      <div class="space-y-3">
        <label class="text-[10px] font-black uppercase tracking-[0.2em] text-gray-400 ml-4">Preço (R$)</label>
        <input 
          type="number" 
          [(ngModel)]="formData.price" 
          name="price"
          class="w-full px-8 py-5 bg-gray-50 border-none rounded-3xl outline-none font-bold text-gray-900 focus:ring-2 focus:ring-primary-600/10 transition-all"
          required
        />
      </div>
    </div>

    <div class="grid grid-cols-2 gap-6">
      <div class="space-y-3">
        <label class="text-[10px] font-black uppercase tracking-[0.2em] text-gray-400 ml-4">Estoque Inicial</label>
        <input 
          type="number" 
          [(ngModel)]="formData.stock" 
          name="stock"
          class="w-full px-8 py-5 bg-gray-50 border-none rounded-3xl outline-none font-bold text-gray-900 focus:ring-2 focus:ring-primary-600/10 transition-all"
          required
        />
      </div>
      <div class="space-y-3">
        <label class="text-[10px] font-black uppercase tracking-[0.2em] text-gray-400 ml-4">Status</label>
        <div class="flex items-center gap-4 px-8 py-5 bg-gray-50 rounded-3xl">
          <input 
            type="checkbox" 
            [(ngModel)]="formData.isActive" 
            name="isActive"
            class="w-6 h-6 rounded-lg text-primary-600 focus:ring-primary-600/20 border-none bg-gray-200"
          />
          <span class="text-xs font-black uppercase tracking-widest text-gray-600">Produto Ativo</span>
        </div>
      </div>
    </div>

    <div class="pt-6 flex gap-4">
      <button 
        type="button"
        (click)="showModal = false"
        class="flex-1 px-8 py-5 rounded-3xl font-black text-xs uppercase tracking-widest text-gray-400 hover:bg-gray-50 transition-all"
      >
        Cancelar
      </button>
      <button 
        type="submit"
        class="flex-2 bg-primary-600 hover:bg-primary-700 text-white font-black px-12 py-5 rounded-3xl shadow-xl shadow-primary-600/20 transition-all active:scale-95"
      >
        Confirmar e Salvar
      </button>
    </div>
  </form>
</app-modal>

// src/UI/Web/React/src/features/products/Products.tsx
import { useState } from 'react';
import { useProducts } from './useProducts';
import Modal from '../../components/Modal';
import ConfirmModal from '../../components/ConfirmModal';
import Pagination from '../../components/Pagination';

export default function Products() {
  const {
    data, isLoading, page, setPage, pageSize, setPageSize,
    deleteProduct, handleExport, createProduct, updateProduct,
    searchTerm, setSearchTerm, isActive, setIsActive
  } = useProducts();
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isDeleteModalOpen, setIsDeleteModalOpen] = useState(false);
  const [productToDelete, setProductToDelete] = useState<number | null>(null);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [formData, setFormData] = useState({ name: '', category: '', price: '', stock: '', isActive: true });

  const handleDelete = (id: number) => {
    setProductToDelete(id);
    setIsDeleteModalOpen(true);
  };

  const confirmDelete = async () => {
    if (productToDelete) {
      await deleteProduct(productToDelete);
      setIsDeleteModalOpen(false);
      setProductToDelete(null);
    }
  };

  const totalPages = data?.totalPages || 1;

  const handleEdit = (product: any) => {
    setEditingId(product.id);
    setFormData({
      name: product.name || '',
      category: product.category || '',
      price: product.price?.toString() || '0',
      stock: product.stock?.toString() || '0',
      isActive: product.isActive ?? true
    });
    setIsModalOpen(true);
  };

  const handleOpenNew = () => {
    setEditingId(null);
    setFormData({ name: '', category: '', price: '', stock: '', isActive: true });
    setIsModalOpen(true);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const payload = {
      ...formData,
      price: parseFloat(formData.price),
      stock: parseInt(formData.stock)
    };

    try {
      if (editingId) {
        await updateProduct({ id: editingId, product: payload });
      } else {
        await createProduct(payload);
      }
      setIsModalOpen(false);
      setFormData({ name: '', category: '', price: '', stock: '', isActive: true });
    } catch (error) {
      alert(`Erro ao ${editingId ? 'atualizar' : 'criar'} produto`);
    }
  };

  return (
    <div className="animate-in fade-in duration-700">
      <header className="flex justify-between items-end mb-16">
        <div>
          <h1 className="text-6xl font-black text-gray-900 tracking-tighter">Produtos</h1>
          <p className="text-gray-500 mt-4 font-medium text-xl">Catálogo completo de itens.</p>
        </div>
        <div className="flex gap-4">
          <button
            onClick={handleExport}
            className="p-4 bg-white border border-gray-100 rounded-2xl shadow-sm hover:shadow-md text-gray-400 hover:text-primary-600 transition-all active:scale-95"
            title="Exportar para Excel"
          >
            📊
          </button>
          <button
            onClick={handleOpenNew}
            className="bg-primary-600 hover:bg-primary-700 text-white font-black px-8 py-4 rounded-2xl shadow-lg shadow-primary-600/20 transition-all active:scale-95"
          >
            + Novo Produto
          </button>
        </div>
      </header>

      {/* Filter Bar */}
      <div className="flex gap-6 items-center mb-10">
        <div className="flex-1 relative group">
          <div className="absolute inset-y-0 left-6 flex items-center pointer-events-none">
            <svg className="w-5 h-5 text-gray-400 group-focus-within:text-primary-600 transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
          </div>
          <input
            type="text"
            placeholder="Buscar por nome ou categoria..."
            className="w-full pl-16 pr-8 py-5 bg-white border-none rounded-3xl shadow-xl shadow-gray-100/50 focus:ring-2 focus:ring-primary-600/20 outline-none transition-all font-bold text-gray-900 placeholder:text-gray-300"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
        </div>

        <div className="flex bg-white p-2 rounded-[2rem] shadow-xl shadow-gray-100/50 gap-1">
          {[
            { label: 'Todos', value: undefined },
            { label: 'Ativos', value: true },
            { label: 'Inativos', value: false }
          ].map((status) => (
            <button
              key={status.label}
              onClick={() => setIsActive(status.value)}
              className={`px-8 py-3 rounded-2xl font-black text-xs uppercase tracking-widest transition-all ${
                isActive === status.value
                ? 'bg-gray-900 text-white shadow-lg'
                : 'text-gray-400 hover:bg-gray-50'
              }`}
            >
              {status.label}
            </button>
          ))}
        </div>
      </div>

      <div className="bg-white rounded-[3rem] shadow-2xl shadow-gray-200/40 border border-gray-50 overflow-hidden">
        <table className="w-full text-left border-collapse">
          <thead className="bg-primary-600">
            <tr>
              <th className="px-10 py-8 text-[10px] font-black text-white uppercase tracking-[0.2em]">Produto</th>
              <th className="px-10 py-8 text-[10px] font-black text-white uppercase tracking-[0.2em]">Categoria</th>
              <th className="px-10 py-8 text-[10px] font-black text-white uppercase tracking-[0.2em]">Preço</th>
              <th className="px-10 py-8 text-[10px] font-black text-white uppercase tracking-[0.2em]">Estoque</th>
              <th className="px-10 py-8 text-[10px] font-black text-white uppercase tracking-[0.2em]">Status</th>
              <th className="px-10 py-8 text-[10px] font-black text-white uppercase tracking-[0.2em]">Ações</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-50">
            {isLoading ? (
              <tr><td colSpan={6} className="p-20 text-center"><div className="w-10 h-10 border-4 border-primary-600 border-t-transparent rounded-full animate-spin mx-auto" /></td></tr>
            ) : data?.items.map((product: any) => (
              <tr key={product.id} className="hover:bg-gray-50/50 transition-colors group">
                <td className="px-10 py-8">
                  <div className="flex items-center gap-6">
                    <div className="w-14 h-14 bg-gray-50 rounded-2xl flex items-center justify-center text-2xl group-hover:scale-110 transition-transform">
                      📦
                    </div>
                    <span className="font-black text-gray-900 text-lg tracking-tight">
                      {product.name}
                    </span>
                  </div>
                </td>
                <td className="px-10 py-8">
                  <span className="px-4 py-2 bg-gray-50 rounded-xl text-gray-500 font-bold text-xs uppercase tracking-wider">
                    {product.category}
                  </span>
                </td>
                <td className="px-10 py-8">
                  <span className="font-black text-primary-600 text-lg">R$ {product.price.toLocaleString('pt-BR')}</span>
                </td>
                <td className="px-10 py-8">
                  <div className="flex items-baseline gap-1">
                    <span className="font-black text-gray-900 text-lg">{product.stock}</span>
                    <span className="text-[10px] font-bold text-gray-300 uppercase tracking-widest">unid</span>
                  </div>
                </td>
                <td className="px-10 py-8">
                  <span className={`px-4 py-2 rounded-xl font-black text-[10px] uppercase tracking-widest ${
                    product.isActive
                    ? 'bg-emerald-50 text-emerald-600'
                    : 'bg-red-50 text-red-600'
                  }`}>
                    {product.isActive ? 'Ativo' : 'Inativo'}
                  </span>
                </td>
                <td className="px-10 py-8">
                  <div className="flex gap-2">
                    <button
                      onClick={() => handleEdit(product)}
                      className="w-10 h-10 flex items-center justify-center bg-gray-50 hover:bg-primary-50 rounded-xl text-primary-600 transition-all active:scale-90"
                      title="Editar"
                    >
                      ✏️
                    </button>
                    <button
                      onClick={() => handleDelete(product.id)}
                      className="w-10 h-10 flex items-center justify-center bg-gray-50 hover:bg-red-50 rounded-xl text-red-600 transition-all active:scale-90"
                      title="Excluir"
                    >
                      🗑️
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        <Pagination
          currentPage={page}
          totalPages={totalPages}
          pageSize={pageSize}
          onPageChange={setPage}
          onPageSizeChange={setPageSize}
        />
      </div>

      {/* Modal Produto */}
      <Modal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title={editingId ? 'Editar Produto' : 'Novo Produto'}
      >
        <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <label className="block text-xs font-black uppercase tracking-widest text-gray-400 mb-2">Nome do Produto</label>
            <input
              required
              className="w-full px-6 py-4 bg-gray-50 border-none rounded-2xl focus:ring-2 focus:ring-primary-600 outline-none transition-all font-bold text-gray-900"
              value={formData.name}
              onChange={e => setFormData({ ...formData, name: e.target.value })}
              placeholder="Ex: Teclado Mecânico"
            />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-black uppercase tracking-widest text-gray-400 mb-2">Preço (R$)</label>
              <input
                required
                type="number" step="0.01"
                className="w-full px-6 py-4 bg-gray-50 border-none rounded-2xl focus:ring-2 focus:ring-primary-600 outline-none transition-all font-bold text-gray-900"
                value={formData.price}
                onChange={e => setFormData({ ...formData, price: e.target.value })}
                placeholder="0.00"
              />
            </div>
            <div>
              <label className="block text-xs font-black uppercase tracking-widest text-gray-400 mb-2">Estoque</label>
              <input
                required
                type="number"
                className="w-full px-6 py-4 bg-gray-50 border-none rounded-2xl focus:ring-2 focus:ring-primary-600 outline-none transition-all font-bold text-gray-900"
                value={formData.stock}
                onChange={e => setFormData({ ...formData, stock: e.target.value })}
                placeholder="0"
              />
            </div>
          </div>
          <div>
            <label className="block text-xs font-black uppercase tracking-widest text-gray-400 mb-2">Categoria</label>
            <input
              required
              className="w-full px-6 py-4 bg-gray-50 border-none rounded-2xl focus:ring-2 focus:ring-primary-600 outline-none transition-all font-bold text-gray-900"
              value={formData.category}
              onChange={e => setFormData({ ...formData, category: e.target.value })}
              placeholder="Ex: Periféricos"
            />
          </div>
          <div className="flex items-center gap-3 bg-gray-50 p-4 rounded-2xl">
            <input
              type="checkbox"
              id="isActive"
              className="w-5 h-5 accent-primary-600"
              checked={formData.isActive}
              onChange={e => setFormData({ ...formData, isActive: e.target.checked })}
            />
            <label htmlFor="isActive" className="text-sm font-bold text-gray-700 cursor-pointer">Produto Ativo</label>
          </div>
          <button
            type="submit"
            className="w-full bg-primary-600 hover:bg-primary-700 text-white font-black py-5 rounded-2xl shadow-xl shadow-primary-600/20 transition-all active:scale-95"
          >
            {editingId ? 'Atualizar Produto' : 'Salvar Produto'}
          </button>
        </form>
      </Modal>

      <ConfirmModal
        isOpen={isDeleteModalOpen}
        message="Deseja excluir este produto?"
        onConfirm={confirmDelete}
        onCancel={() => setIsDeleteModalOpen(false)}
      />
    </div>
  );
}
