// src/UI/Web/React/src/features/documents/Documents.tsx
import { useState } from 'react';
import { documentService } from '../../api/services/document.service';
import { CloudUpload, Download, Trash2, FileCode } from 'lucide-react';

export default function Documents() {
  const [fileName, setFileName] = useState('');
  const [uploading, setUploading] = useState(false);
  const [processing, setProcessing] = useState(false);

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setUploading(true);
      try {
        const res = await documentService.upload(file);
        setFileName(res.fileName);
      } finally {
        setUploading(false);
      }
    }
  };

  const handleDownload = async () => {
    if (!fileName) return;
    setProcessing(true);
    try {
      const response = await documentService.download(fileName);
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', fileName);
      document.body.appendChild(link);
      link.click();
      link.remove();
    } finally {
      setProcessing(false);
    }
  };

  const handleDelete = async () => {
    if (!fileName) return;
    setProcessing(true);
    try {
      await documentService.delete(fileName);
      setFileName('');
    } finally {
      setProcessing(false);
    }
  };

  return (
    <div className="animate-in fade-in slide-in-from-bottom-4 duration-700 max-w-4xl mx-auto py-10">
      <div className="mb-16 text-center">
        <h1 className="text-6xl font-black text-gray-900 tracking-tighter">Cloud Storage</h1>
        <p className="text-gray-500 mt-4 font-medium text-xl">Upload, download e gerenciamento direto de arquivos.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
        {/* Upload Section */}
        <div className="bg-white p-12 rounded-[3.5rem] shadow-2xl shadow-gray-200/60 border border-gray-50 flex flex-col items-center gap-8 group">
          <div className="w-32 h-32 bg-primary-50 rounded-[2.5rem] flex items-center justify-center text-primary-600 transition-transform group-hover:scale-110 duration-500">
            {uploading ? (
              <div className="w-12 h-12 border-4 border-primary-100 border-t-primary-600 rounded-full animate-spin" />
            ) : (
              <CloudUpload size={64} />
            )}
          </div>
          
          <div className="text-center">
            <h3 className="text-2xl font-black text-gray-900 mb-2">Novo Upload</h3>
            <p className="text-gray-400 text-sm font-medium">Selecione um arquivo para subir</p>
          </div>

          <label className="w-full cursor-pointer">
            <input type="file" className="hidden" onChange={handleFileChange} disabled={uploading} />
            <div className="w-full py-5 bg-gray-900 text-white rounded-2xl font-black text-center hover:bg-black transition-all shadow-lg shadow-gray-200 active:scale-95">
              Selecionar Arquivo
            </div>
          </label>
        </div>

        {/* Management Section */}
        <div className="bg-white p-12 rounded-[3.5rem] shadow-2xl shadow-gray-200/60 border border-gray-50 flex flex-col gap-8">
          <div>
            <h3 className="text-2xl font-black text-gray-900 mb-2">Gerenciar Arquivo</h3>
            <p className="text-gray-400 text-sm font-medium">Digite o nome do arquivo para as ações</p>
          </div>

          <div className="space-y-4">
            <div className="relative">
              <input 
                type="text" 
                value={fileName}
                onChange={(e) => setFileName(e.target.value)}
                placeholder="ex: contrato_v1.pdf"
                className="w-full px-6 py-5 bg-gray-50 border-none rounded-2xl font-bold text-gray-700 placeholder:text-gray-300 focus:ring-2 focus:ring-primary-500 transition-all outline-none"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <button 
                onClick={handleDownload}
                disabled={!fileName || processing}
                className="py-5 bg-primary-50 text-primary-600 rounded-2xl font-black hover:bg-primary-100 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                <Download size={20} />
                Download
              </button>
              
              <button 
                onClick={handleDelete}
                disabled={!fileName || processing}
                className="py-5 bg-rose-50 text-rose-600 rounded-2xl font-black hover:bg-rose-100 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                <Trash2 size={20} />
                Deletar
              </button>
            </div>
          </div>

          {processing && (
            <div className="flex items-center justify-center gap-3 text-primary-600 font-bold animate-pulse">
              <div className="w-2 h-2 bg-primary-600 rounded-full"></div>
              Processando...
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// src/UI/Web/Angular/src/app/features/documents/pages/documents.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';

import { FormsModule } from '@angular/forms';
import { DocumentService } from '../../../core/services/document.service';

@Component({
  selector: 'app-documents',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './documents.component.html'
})
export class DocumentsComponent {
  private documentService = inject(DocumentService);
  
  fileName = signal('');
  uploading = signal(false);
  processing = signal(false);

  onFileSelected(event: Event) {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (file) {
      this.uploadFile(file);
    }
  }

  uploadFile(file: File) {
    this.uploading.set(true);
    this.documentService.upload(file).subscribe({
      next: (res) => {
        this.fileName.set(res.fileName);
        this.uploading.set(false);
        // Toast success logic could go here
      },
      error: () => this.uploading.set(false)
    });
  }

  downloadFile() {
    if (!this.fileName()) return;
    this.processing.set(true);
    this.documentService.download(this.fileName()).subscribe({
      next: (blob) => {
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = this.fileName();
        a.click();
        window.URL.revokeObjectURL(url);
        this.processing.set(false);
      },
      error: () => this.processing.set(false)
    });
  }

  deleteFile() {
    if (!this.fileName()) return;
    this.processing.set(true);
    this.documentService.delete(this.fileName()).subscribe({
      next: () => {
        this.fileName.set('');
        this.processing.set(false);
      },
      error: () => this.processing.set(false)
    });
  }
}

<div class="animate-in fade-in slide-in-from-bottom-4 duration-700 max-w-4xl mx-auto">
  <div class="mb-16 text-center">
    <h1 class="text-6xl font-black text-gray-900 tracking-tighter">Cloud Storage</h1>
    <p class="text-gray-500 mt-4 font-medium text-xl">Upload, download e gerenciamento direto de arquivos.</p>
  </div>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-10">
    <!-- Upload Section -->
    <div class="bg-white p-12 rounded-[3.5rem] shadow-2xl shadow-gray-200/60 border border-gray-50 flex flex-col items-center gap-8 group">
      <div class="w-32 h-32 bg-primary-50 rounded-[2.5rem] flex items-center justify-center text-primary-600 transition-transform group-hover:scale-110 duration-500">
        @if (uploading()) {
          <div class="w-12 h-12 border-4 border-primary-100 border-t-primary-600 rounded-full animate-spin"></div>
        } @else {
          <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
          </svg>
        }
      </div>
      
      <div class="text-center">
        <h3 class="text-2xl font-black text-gray-900 mb-2">Novo Upload</h3>
        <p class="text-gray-400 text-sm font-medium">Arraste ou selecione um arquivo</p>
      </div>

      <label class="w-full">
        <input type="file" class="hidden" (change)="onFileSelected($event)" [disabled]="uploading()">
        <div class="w-full py-5 bg-gray-900 text-white rounded-2xl font-black text-center cursor-pointer hover:bg-black transition-all shadow-lg shadow-gray-200 active:scale-95">
          Selecionar Arquivo
        </div>
      </label>
    </div>

    <!-- Management Section -->
    <div class="bg-white p-12 rounded-[3.5rem] shadow-2xl shadow-gray-200/60 border border-gray-50 flex flex-col gap-8">
      <div>
        <h3 class="text-2xl font-black text-gray-900 mb-2">Gerenciar Arquivo</h3>
        <p class="text-gray-400 text-sm font-medium">Digite o nome do arquivo para as ações</p>
      </div>

      <div class="space-y-4">
        <div class="relative">
          <input 
            type="text" 
            [(ngModel)]="fileName"
            placeholder="ex: contrato_v1.pdf"
            class="w-full px-6 py-5 bg-gray-50 border-none rounded-2xl font-bold text-gray-700 placeholder:text-gray-300 focus:ring-2 focus:ring-primary-500 transition-all"
          >
        </div>

        <div class="grid grid-cols-2 gap-4">
          <button 
            (click)="downloadFile()"
            [disabled]="!fileName() || processing()"
            class="py-5 bg-primary-50 text-primary-600 rounded-2xl font-black hover:bg-primary-100 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
          >
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download
          </button>
          
          <button 
            (click)="deleteFile()"
            [disabled]="!fileName() || processing()"
            class="py-5 bg-rose-50 text-rose-600 rounded-2xl font-black hover:bg-rose-100 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
          >
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
            </svg>
            Deletar
          </button>
        </div>
      </div>

      @if (processing()) {
        <div class="flex items-center justify-center gap-3 text-primary-600 font-bold animate-pulse">
          <div class="w-2 h-2 bg-primary-600 rounded-full"></div>
          Processando...
        </div>
      }
    </div>
  </div>
</div>
