// src/UI/Web/Vue/src/components/Modal.vue
<script setup lang="ts">
defineProps<{
  show: boolean;
  title: string;
}>();

defineEmits(['close']);
</script>

<template>
  <Teleport to="body">
    <Transition
      enter-active-class="transition duration-300 ease-out"
      enter-from-class="opacity-0"
      enter-to-class="opacity-100"
      leave-active-class="transition duration-200 ease-in"
      leave-from-class="opacity-100"
      leave-to-class="opacity-0"
    >
      <div v-if="show" class="fixed inset-0 z-50 flex items-center justify-center p-4">
        <div class="absolute inset-0 bg-gray-900/40 backdrop-blur-sm" @click="$emit('close')"></div>
        
        <Transition
          enter-active-class="transition duration-300 ease-out"
          enter-from-class="transform scale-95 opacity-0"
          enter-to-class="transform scale-100 opacity-100"
          leave-active-class="transition duration-200 ease-in"
          leave-from-class="transform scale-100 opacity-100"
          leave-to-class="transform scale-95 opacity-0"
        >
          <div class="bg-white rounded-[3rem] shadow-2xl w-full max-w-lg relative z-10 overflow-hidden">
            <div class="px-10 pt-10 pb-6 flex justify-between items-center border-b border-gray-50">
              <h2 class="text-3xl font-black text-gray-900 tracking-tighter">{{ title }}</h2>
              <button @click="$emit('close')" class="text-gray-300 hover:text-gray-900 transition-colors">
                <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <div class="p-10">
              <slot></slot>
            </div>
          </div>
        </Transition>
      </div>
    </Transition>
  </Teleport>
</template>

// src/UI/Web/Angular/src/app/shared/components/modal/modal.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-modal',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div *ngIf="show" class="fixed inset-0 z-50 flex items-center justify-center p-4 animate-in fade-in duration-300">
      <div class="absolute inset-0 bg-gray-900/40 backdrop-blur-sm" (click)="onClose()"></div>
      <div class="bg-white rounded-[3rem] shadow-2xl w-full max-w-lg relative z-10 overflow-hidden animate-in zoom-in-95 duration-300">
        <div class="px-10 pt-10 pb-6 flex justify-between items-center border-b border-gray-50">
          <h2 class="text-3xl font-black text-gray-900 tracking-tighter">{{ title }}</h2>
          <button (click)="onClose()" class="text-gray-300 hover:text-gray-900 transition-colors">
            <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <div class="p-10">
          <ng-content></ng-content>
        </div>
      </div>
    </div>
  `
})
export class ModalComponent {
  @Input() show = false;
  @Input() title = '';
  @Output() close = new EventEmitter<void>();

  onClose() {
    this.close.emit();
  }
}

<div *ngIf="show" class="fixed inset-0 z-50 flex items-center justify-center p-4 animate-in fade-in duration-300">
  <div class="absolute inset-0 bg-gray-900/40 backdrop-blur-sm" (click)="onClose()"></div>
  <div class="bg-white rounded-[3rem] shadow-2xl w-full {{ maxWidth }} relative z-10 overflow-hidden animate-in zoom-in-95 duration-300">
    <div class="px-10 pt-10 pb-6 flex justify-between items-center border-b border-gray-50">
      <h2 class="text-3xl font-black text-gray-900 tracking-tighter">{{ title }}</h2>
      <button (click)="onClose()" class="text-gray-300 hover:text-gray-900 transition-colors">
        <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>
    <div class="p-10">
      <ng-content></ng-content>
    </div>
  </div>
</div>
