// src/UI/Web/Vue/src/features/orders/components/OrderDetailsModal.vue
<template>
  <div v-if="isOpen" class="fixed inset-0 z-50 flex items-center justify-end">
    <!-- Backdrop -->
    <div class="absolute inset-0 bg-gray-900/40 backdrop-blur-sm transition-opacity" @click="$emit('onClose')"></div>

    <!-- Modal Content -->
    <div class="relative h-full w-full max-w-2xl bg-white shadow-2xl flex flex-col animate-slide-in print-area">
      <template v-if="order">
        <!-- Header -->
        <div class="p-8 border-b border-gray-100 flex justify-between items-center bg-gray-50/50">
          <div>
            <h2 class="text-2xl font-black text-gray-900">Pedido #{{ order.orderNumber }}</h2>
            <p class="text-gray-500 text-sm mt-1">Realizado em {{ formatDate(order.createdAt) }}</p>
          </div>
          <button @click="$emit('onClose')" class="p-2 hover:bg-gray-200 rounded-xl transition-all">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <!-- Body -->
        <div class="flex-1 overflow-y-auto p-8 space-y-10">
          <!-- Status & Info -->
          <div class="grid grid-cols-2 gap-8">
            <div>
              <p class="text-[10px] uppercase tracking-widest text-gray-400 font-bold mb-2">Status do Pedido</p>
              <span :class="['px-4 py-2 rounded-xl text-xs font-bold uppercase tracking-widest', getStatusClass(order.status)]">
                {{ order.status }}
              </span>
            </div>
            <div>
              <p class="text-[10px] uppercase tracking-widest text-gray-400 font-bold mb-2">Cliente</p>
              <p class="font-bold text-gray-900">{{ order.customerName }}</p>
              <p class="text-xs text-gray-500">{{ order.customerEmail }}</p>
            </div>
          </div>

          <!-- Items Table -->
          <div>
            <p class="text-[10px] uppercase tracking-widest text-gray-400 font-bold mb-4">Itens do Pedido</p>
            <div class="bg-gray-50 rounded-3xl overflow-hidden border border-gray-100">
              <table class="w-full text-left">
                <thead class="bg-gray-100/50 text-[10px] uppercase text-gray-400">
                  <tr>
                    <th class="px-6 py-4">Produto</th>
                    <th class="px-6 py-4 text-center">Qtd</th>
                    <th class="px-6 py-4 text-right">Preço</th>
                    <th class="px-6 py-4 text-right">Total</th>
                  </tr>
                </thead>
                <tbody class="divide-y divide-gray-100">
                  <tr v-for="item in order.items" :key="item.productId">
                    <td class="px-6 py-4">
                      <p class="text-sm font-bold text-gray-800">{{ item.productName }}</p>
                      <p class="text-[10px] text-gray-400">ID: {{ item.productId }}</p>
                    </td>
                    <td class="px-6 py-4 text-center text-sm font-medium text-gray-600">{{ item.quantity }}</td>
                    <td class="px-6 py-4 text-right text-sm text-gray-600">R$ {{ item.unitPrice.toLocaleString('pt-BR') }}</td>
                    <td class="px-6 py-4 text-right text-sm font-bold text-gray-900">R$ {{ item.subtotal.toLocaleString('pt-BR') }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <!-- Shipping Address -->
          <div>
            <p class="text-[10px] uppercase tracking-widest text-gray-400 font-bold mb-2">Endereço de Entrega</p>
            <div class="p-5 bg-primary-50/30 rounded-2xl border border-primary-100/50 flex gap-4">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-primary-600 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
              </svg>
              <p class="text-sm text-gray-700 leading-relaxed">{{ order.shippingAddress }}</p>
            </div>
          </div>
        </div>

        <!-- Footer / Totals -->
        <div class="p-8 border-t border-gray-100 bg-gray-50/30">
          <div class="space-y-3">
            <div class="flex justify-between text-sm">
              <span class="text-gray-500">Subtotal</span>
              <span class="font-medium text-gray-900">R$ {{ order.subtotal.toLocaleString('pt-BR') }}</span>
            </div>
            <div class="flex justify-between text-sm">
              <span class="text-gray-500">Frete</span>
              <span class="font-medium text-gray-900">R$ {{ order.shippingCost.toLocaleString('pt-BR') }}</span>
            </div>
            <div class="flex justify-between text-sm">
              <span class="text-gray-500">Impostos</span>
              <span class="font-medium text-gray-900">R$ {{ order.tax.toLocaleString('pt-BR') }}</span>
            </div>
            <div class="pt-4 border-t border-gray-200 flex justify-between items-end">
              <span class="text-lg font-bold text-gray-900">Total</span>
              <span class="text-3xl font-black text-primary-600">R$ {{ order.total.toLocaleString('pt-BR') }}</span>
            </div>
          </div>
          
          <div class="mt-10 flex gap-4 no-print">
            <button @click="print" class="flex-1 bg-gradient-to-br from-primary-50/50 to-white border border-primary-100 py-4 rounded-2xl text-[11px] font-bold text-primary-700 uppercase tracking-widest hover:bg-white hover:border-primary-200 hover:shadow-lg hover:shadow-primary-100/50 transition-all active:scale-95 flex items-center justify-center gap-3">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-primary-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
              </svg>
              Imprimir Pedido
            </button>
            <div class="flex-1">
              <Dropdown 
                v-model="orderStatus"
                :options="statusOptions"
                variant="primary"
                labelOverride="Atualizar Status"
                direction="up"
                @change="handleStatusChange"
              />
            </div>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { orderService } from '../../../api/services/OrderService';
import Dropdown from '../../../components/Dropdown.vue';

const props = defineProps<{
  isOpen: boolean;
  order: any;
}>();

const emit = defineEmits(['onClose', 'onStatusUpdated']);

const orderStatus = ref('');
const statusOptions = [
  { label: 'Pendente', value: 'Pending' },
  { label: 'Enviado', value: 'Shipped' },
  { label: 'Entregue', value: 'Delivered' },
  { label: 'Cancelado', value: 'Cancelled' }
];

watch(() => props.order, (newOrder) => {
  if (newOrder) orderStatus.value = newOrder.status;
});

const handleStatusChange = async (newStatus: string) => {
  if (!props.order) return;
  try {
    await orderService.updateStatus(props.order.id, newStatus, 'Atualizado via Dashboard Vue');
    emit('onStatusUpdated');
  } catch (error) {
    alert('Erro ao atualizar status');
  }
};

const print = () => window.print();

const formatDate = (date: string) => {
  return new Date(date).toLocaleString('pt-BR');
};

const getStatusClass = (status: string) => {
  switch (status?.toLowerCase()) {
    case 'pending': return 'bg-amber-50 text-amber-600';
    case 'completed': return 'bg-emerald-50 text-emerald-600';
    case 'cancelled': return 'bg-rose-50 text-rose-600';
    case 'shipped': return 'bg-indigo-50 text-indigo-600';
    default: return 'bg-gray-50 text-gray-600';
  }
};
</script>

<style scoped>
@keyframes slideIn {
  from { transform: translateX(100%); }
  to { transform: translateX(0); }
}
.animate-slide-in {
  animation: slideIn 0.3s ease-out forwards;
}
@media print {
  .no-print { display: none; }
}
</style>

// src/UI/Web/React/src/features/orders/components/OrderDetailsModal.tsx
import React from 'react';
import { OrderResponseDto, orderService } from '../../../api/services';
import Dropdown from '../../../components/Dropdown';

interface OrderDetailsModalProps {
  order: OrderResponseDto | null;
  isOpen: boolean;
  onClose: () => void;
  onStatusUpdated: () => void;
}

const OrderDetailsModal: React.FC<OrderDetailsModalProps> = ({ order, isOpen, onClose, onStatusUpdated }) => {
  if (!isOpen || !order) return null;

  const handleStatusChange = async (newStatus: string) => {
    if (!order || newStatus === order.status) return;

    try {
      await orderService.updateStatus(order.id, newStatus);
      onStatusUpdated();
    } catch (error) {
      alert('Erro ao atualizar status');
    }
  };

  const getStatusClass = (status: string) => {
    switch (status.toLowerCase()) {
      case 'pending': return 'bg-amber-50 text-amber-600';
      case 'completed': return 'bg-emerald-50 text-emerald-600';
      case 'cancelled': return 'bg-rose-50 text-rose-600';
      case 'shipped': return 'bg-indigo-50 text-indigo-600';
      default: return 'bg-gray-50 text-gray-600';
    }
  };

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-end">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-gray-900/40 backdrop-blur-sm transition-opacity" 
        onClick={onClose}
      />

      {/* Modal Content */}
      <div className="relative h-full w-full max-w-2xl bg-white shadow-2xl flex flex-col animate-in slide-in-from-right duration-300 print-area">
        {/* Header */}
        <div className="p-8 border-b border-gray-100 flex justify-between items-center bg-gray-50/50">
          <div>
            <h2 className="text-2xl font-black text-gray-900 tracking-tight">Pedido #{order.orderNumber}</h2>
            <p className="text-gray-500 text-sm mt-1 italic font-medium">
              Realizado em {new Date(order.createdAt).toLocaleString('pt-BR')}
            </p>
          </div>
          <button 
            onClick={onClose}
            className="p-3 hover:bg-gray-100 rounded-2xl transition-all active:scale-90 no-print"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-8 space-y-10">
          {/* Status & Info */}
          <div className="grid grid-cols-2 gap-8">
            <div className="space-y-3">
              <p className="text-[10px] uppercase tracking-[0.2em] text-gray-400 font-black">Status do Pedido</p>
              <span className={`px-5 py-2.5 rounded-2xl text-[10px] font-black uppercase tracking-[0.1em] shadow-sm ${getStatusClass(order.status)}`}>
                {order.status}
              </span>
            </div>
            <div className="space-y-1">
              <p className="text-[10px] uppercase tracking-[0.2em] text-gray-400 font-black mb-3">Cliente</p>
              <p className="font-black text-gray-900 text-lg leading-none tracking-tight">{order.customerName}</p>
              <p className="text-xs text-gray-400 font-bold uppercase tracking-widest">{order.customerEmail}</p>
            </div>
          </div>

          {/* Items Table */}
          <div className="space-y-4">
            <p className="text-[10px] uppercase tracking-[0.2em] text-gray-400 font-black">Itens do Pedido</p>
            <div className="bg-gray-50 rounded-[2.5rem] overflow-hidden border border-gray-100 shadow-xl shadow-gray-100/20">
              <table className="w-full text-left">
                <thead className="bg-gray-100/50 text-[10px] font-black uppercase tracking-widest text-gray-400">
                  <tr>
                    <th className="px-8 py-5">Produto</th>
                    <th className="px-8 py-5 text-center">Qtd</th>
                    <th className="px-8 py-5 text-right">Preço</th>
                    <th className="px-8 py-5 text-right">Total</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {order.items.map((item, index) => (
                    <tr key={index} className="hover:bg-white transition-colors group">
                      <td className="px-8 py-6">
                        <p className="text-sm font-black text-gray-800 tracking-tight">{item.productName}</p>
                        <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mt-0.5">ID: {item.productId}</p>
                      </td>
                      <td className="px-8 py-6 text-center">
                        <span className="inline-flex items-center justify-center w-8 h-8 bg-white rounded-lg text-sm font-black text-gray-600 shadow-sm border border-gray-50">
                          {item.quantity}
                        </span>
                      </td>
                      <td className="px-8 py-6 text-right text-sm font-medium text-gray-500 italic">{formatCurrency(item.unitPrice)}</td>
                      <td className="px-8 py-6 text-right text-sm font-black text-gray-900">{formatCurrency(item.subtotal)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Shipping Address */}
          <div className="space-y-4">
            <p className="text-[10px] uppercase tracking-[0.2em] text-gray-400 font-black">Endereço de Entrega</p>
            <div className="p-6 bg-blue-50/40 rounded-[2rem] border border-blue-100/50 flex gap-5 items-start">
              <div className="w-12 h-12 bg-white rounded-2xl flex items-center justify-center shadow-sm shrink-0 border border-blue-50">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                </svg>
              </div>
              <p className="text-sm text-gray-700 leading-relaxed font-bold italic pt-1">{order.shippingAddress}</p>
            </div>
          </div>
        </div>

        {/* Footer / Totals */}
        <div className="p-8 border-t border-gray-100 bg-gray-50/50">
          <div className="space-y-4 px-4">
            <div className="flex justify-between text-sm">
              <span className="text-gray-400 font-black uppercase tracking-[0.2em] text-[10px]">Subtotal</span>
              <span className="font-black text-gray-900 tracking-tight">{formatCurrency(order.subtotal)}</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-gray-400 font-black uppercase tracking-[0.2em] text-[10px]">Frete</span>
              <span className="font-black text-gray-900 tracking-tight">{formatCurrency(order.shippingCost)}</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-gray-400 font-black uppercase tracking-[0.2em] text-[10px]">Impostos</span>
              <span className="font-black text-gray-900 tracking-tight">{formatCurrency(order.tax)}</span>
            </div>
            <div className="pt-6 mt-2 border-t border-gray-200 flex justify-between items-end">
              <span className="text-lg font-black text-gray-900 uppercase tracking-tighter">Total</span>
              <span className="text-5xl font-black text-blue-600 tracking-tighter tabular-nums drop-shadow-sm">
                {formatCurrency(order.total)}
              </span>
            </div>
          </div>
          
          <div className="mt-10 flex gap-4 no-print">
            <button 
              onClick={() => window.print()}
              className="flex-1 bg-gradient-to-br from-gray-50 to-white border border-gray-200 py-4 rounded-2xl text-[11px] font-bold text-gray-700 uppercase tracking-widest hover:bg-white hover:border-gray-300 hover:shadow-lg hover:shadow-gray-100 transition-all active:scale-95 flex items-center justify-center gap-3"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
              </svg>
              Imprimir Pedido
            </button>
            <div className="flex-1">
              <Dropdown 
                variant="primary"
                value={order.status}
                onChange={handleStatusChange}
                placeholder="Atualizar Status"
                labelOverride="Atualizar Status"
                direction="up"
                options={[
                  { label: 'Pendente', value: 'Pending' },
                  { label: 'Enviado', value: 'Shipped' },
                  { label: 'Entregue', value: 'Delivered' },
                  { label: 'Cancelado', value: 'Cancelled' }
                ]}
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default OrderDetailsModal;
